### PR TITLE
Korean locale update

### PR DESCRIPTION
**Pull request by AGPumBoy**
Korean locale strings update.

- [x] Update XML Korean Strings
  - [x] Update korean settings.xml
  - [x] Update korean reaply.xml
  - [x] Update korean multiplayer.xml
  - [x] Update korean menus.xml
  - [x] Update korean general.xml
  - [x] Update korean dialogs.xml

- [x] Check File
  - [x] Edit all untranslated strings
  - [x] Edit all mistranslation strings
  - [x] Grammar alignment

- [x] Ready for review merge commit

### CODE REVIEW

**Comment by AGPumBoy** [comment]
Work In Progress(Not Done)

**Comment by AGPumBoy** [comment]
Done. Ready for review this pull request.

**Comment by Acivev** [comment]
haha, good one. One day I will definitely be able to read and write Korean 😂😂
You can ask the community in the international server

**Comment by AGPumBoy** [comment]
First Merge. I'll ask the Korean osu!droid community.

**Pull request merged**
